name: Notify Reviewers on PR

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Get PR reviewers
        id: reviewers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          REPO="${{ github.repository }}"

          echo "Fetching reviewers for PR #$PR_NUMBER from $REPO"

          API_RESPONSE=$(gh api repos/$REPO/pulls/$PR_NUMBER 2>/dev/null || echo "")

          if [ -z "$API_RESPONSE" ]; then
            echo "No response from GitHub API, assuming no reviewers"
            REVIEWERS="[]"
          else
            REVIEWERS=$(echo "$API_RESPONSE" | jq -c '[.requested_reviewers[].login] // []')
          fi

          echo "Reviewers JSON: $REVIEWERS"
          # JSON 문자열을 이중 인용부호 포함하여 출력값에 안전하게 저장
          echo "reviewers=$(printf '%q' "$REVIEWERS")" >> "$GITHUB_OUTPUT"

      - name: Notify Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          USER_MAP: ${{ secrets.USER_MAP }}
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_URL="${{ github.event.pull_request.html_url }}"

          # REVIEWERS는 JSON 문자열임
          REVIEWERS_JSON="${{ steps.reviewers.outputs.reviewers }}"
          REVIEWERS=$(echo "$REVIEWERS_JSON" | jq -c '.')  # validate/normalize

          echo "Notifying Discord about PR: $PR_TITLE"
          echo "Reviewers to mention: $REVIEWERS"

          MENTION_LIST=""

          for user in $(echo "$REVIEWERS" | jq -r '.[]'); do
            DISCORD_ID=$(echo "$USER_MAP" | jq -r --arg u "$user" '.[$u] // empty')
            if [ -n "$DISCORD_ID" ]; then
              MENTION_LIST="$MENTION_LIST <@$DISCORD_ID>"
            else
              MENTION_LIST="$MENTION_LIST @$user"
            fi
          done

          if [ -z "$MENTION_LIST" ]; then
            MENTION_LIST="(리뷰어가 지정되지 않았습니다)"
          fi

          curl -X POST "$DISCORD_WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d @- <<EOF
          {
            "content": "${MENTION_LIST}\n새로운 Pull Request: **${PR_TITLE}**\n${PR_URL}"
          }
          EOF
